---
title: "Emulated RSL densities"
output:
  pdf_document: default
  html_document: default
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## Emulated RSL densities

Here we plot emulated densities of regional sea-level change using a neural-network emulator.

```{r}
#update to where emulated_data_fig8.RData file is located
load("/Users/myungsooyoo/Downloads/emulated_data_fig8.RData")
```

## Including Plots


```{r}
location_lab <- c(rep('Dunedin', 100), rep('Montevideo', 100), rep('Midway', 100))
locations <- factor(location_lab)
#indices 17, 5, and 25 correspond to Dunedin, Montevideo, and Midway 
RSL <- c(mean_test_new[,17], mean_test_new[,5], mean_test_new[,25])
full_dat <- data.frame(locations, RSL)
names(full_dat) <- c('location', 'RSL')
p<-ggplot(full_dat, aes(x=RSL, fill=location)) +
  geom_density(alpha=0.3) + xlim(-.1, .2)
p <- p + ggtitle('Emulated RSL densities') + theme(plot.title = element_text(hjust = 0.5, size = 20))
p <- p + theme(legend.text = element_text(size =20), legend.title = element_text(size = 20))
p <- p + theme(axis.title.x = element_text(size = 20), axis.title.y = element_text(size = 20))
p <- p + theme(axis.text = element_text(size = 15))
p
```

