---
title: "Emulated RSL densities"
output:
  pdf_document: default
  html_document: default
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## Emulated RSL densities

Here we plot emulated densities of regional sea-level change using both kernel and NN emulators.

```{r}
#set working directory to be were Random_Ensemble_new_2 is
#setwd(...)
files_list <- list.files('./Random_Ensemble_new_2/synthetic_pca_ais_dataset_kernel_output')
Dunedin_dat <- rep(0,100)
Montevideo_dat <- rep(0,100)
Midway_dat <- rep(0,100)
for(i in 1:length(files_list)){
  cur_file <- paste('./Random_Ensemble_new_2/synthetic_pca_ais_dataset_kernel_output/', files_list[i], sep ="")
  cur_dat <- read.csv(cur_file, header = FALSE)
  Dunedin_dat[i] <- cur_dat[17,1]
  Montevideo_dat[i] <- cur_dat[5,1]
  Midway_dat[i] <- cur_dat[25,1]
}
```


## Including Plots


```{r}
#kernel densities
location_lab <- c(rep('Dunedin', 100), rep('Montevideo', 100), rep('Midway', 100))
locations <- factor(location_lab)
RSL <- c(Dunedin_dat, Montevideo_dat, Midway_dat)

full_dat <- data.frame(locations, RSL)
names(full_dat) <- c('location', 'RSL')
p<-ggplot(full_dat, aes(x=RSL, fill=location)) +
  geom_density(alpha=0.3) + xlim(-.2, .5)
p <- p + ggtitle('Emulated RSL densities using kernel') + theme(plot.title = element_text(hjust = 0.5, size = 18))
p <- p + theme(legend.text = element_text(size =18), legend.title = element_text(size = 18))
p <- p + theme(axis.title.x = element_text(size = 18), axis.title.y = element_text(size = 18))
p <- p + theme(axis.text = element_text(size = 15))
p
```
```{r}
#NN densities
#set working directory to be where location_nn.csv files are 
#setwd(...)
location_lab <- c(rep('Dunedin', 100), rep('Montevideo', 100), rep('Midway', 100))
locations <- factor(location_lab)
Montevideo_dat <- read.csv('./Montevideo_nn.csv', header = FALSE)[,1]
Dunedin_dat <-  read.csv('./Dunedin_nn.csv', header = FALSE)[,1]
Midway_dat <- read.csv('./Midway_nn.csv', header = FALSE)[,1]

RSL <- c(Dunedin_dat, Montevideo_dat, Midway_dat)

full_dat <- data.frame(locations, RSL)
names(full_dat) <- c('location', 'RSL')
p<-ggplot(full_dat, aes(x=RSL, fill=location)) +
  geom_density(alpha=0.3) + xlim(-.1, .3)
p <- p + ggtitle('Emulated RSL densities using NN') + theme(plot.title = element_text(hjust = 0.5, size = 18))
p <- p + theme(legend.text = element_text(size =18), legend.title = element_text(size = 18))
p <- p + theme(axis.title.x = element_text(size = 18), axis.title.y = element_text(size = 18))
p <- p + theme(axis.text = element_text(size = 15))
p
```


